/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardrobeRouteImport } from './routes/wardrobe'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodayLooksRouteImport } from './routes/today.looks'
import { Route as OutfitIdRouteImport } from './routes/outfit.$id'

const WardrobeRoute = WardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayLooksRoute = TodayLooksRouteImport.update({
  id: '/looks',
  path: '/looks',
  getParentRoute: () => TodayRoute,
} as any)
const OutfitIdRoute = OutfitIdRouteImport.update({
  id: '/outfit/$id',
  path: '/outfit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRouteWithChildren
  '/wardrobe': typeof WardrobeRoute
  '/outfit/$id': typeof OutfitIdRoute
  '/today/looks': typeof TodayLooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRouteWithChildren
  '/wardrobe': typeof WardrobeRoute
  '/outfit/$id': typeof OutfitIdRoute
  '/today/looks': typeof TodayLooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRouteWithChildren
  '/wardrobe': typeof WardrobeRoute
  '/outfit/$id': typeof OutfitIdRoute
  '/today/looks': typeof TodayLooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/saved'
    | '/settings'
    | '/today'
    | '/wardrobe'
    | '/outfit/$id'
    | '/today/looks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/saved'
    | '/settings'
    | '/today'
    | '/wardrobe'
    | '/outfit/$id'
    | '/today/looks'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/saved'
    | '/settings'
    | '/today'
    | '/wardrobe'
    | '/outfit/$id'
    | '/today/looks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRouteWithChildren
  WardrobeRoute: typeof WardrobeRoute
  OutfitIdRoute: typeof OutfitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wardrobe': {
      id: '/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof WardrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today/looks': {
      id: '/today/looks'
      path: '/looks'
      fullPath: '/today/looks'
      preLoaderRoute: typeof TodayLooksRouteImport
      parentRoute: typeof TodayRoute
    }
    '/outfit/$id': {
      id: '/outfit/$id'
      path: '/outfit/$id'
      fullPath: '/outfit/$id'
      preLoaderRoute: typeof OutfitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TodayRouteChildren {
  TodayLooksRoute: typeof TodayLooksRoute
}

const TodayRouteChildren: TodayRouteChildren = {
  TodayLooksRoute: TodayLooksRoute,
}

const TodayRouteWithChildren = TodayRoute._addFileChildren(TodayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRouteWithChildren,
  WardrobeRoute: WardrobeRoute,
  OutfitIdRoute: OutfitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
